import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import BodyParagraph from '../components/BodyParagraph'
import Header from '../components/header'
import Works from '../components/Works'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jeff's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            rel="preload"
            href="/fonts/LexendDeca-Bold.ttf"
            as="font"
            crossOrigin=""
          />
          <link
            rel="preload"
            href="/fonts/LexendDeca-Regular.ttf"
            as="font"
            crossOrigin=""
          />
      </Head>

      <Header/>

      <BodyParagraph/>

      <Works/>

      <div className="min-h-screen bg-white">

      </div>

    </div>
  )
}

export default Home
